---
name: 🍎 MacOS
on:
  push:
    branches:
      - main
# TODO: probably create a nightly job

jobs:
  package:
    runs-on: macos-13
    strategy:
      matrix:
        include:
          - platform: 'osx-64'
            #          - platform: 'osx-arm64'

    name: Package for macOS
    steps:
      - name: 🐣 Checkout
        uses: actions/checkout@v3

      - name: 🐣 Checkout Constructor
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: opengisch/constructor
          ref: qgis-bundling
          path: constructor

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: "constructor"

      - name: 🌾 Get latest version
        shell: bash
        run: |
          QGIS_VERSION=$(conda search -c conda-forge -f qgis | grep py311 | tail -n 1 | tr -s ' ' | cut -f 2 -d ' ')
          QGIS_VERSION_SHORT=$(echo $QGIS_VERSION | cut -d'.'  -f 1,2)
          echo QGIS_VERSION=$QGIS_VERSION >> $GITHUB_ENV
          echo QGIS_VERSION_SHORT=$QGIS_VERSION_SHORT >> $GITHUB_ENV

          sed -i '' "s/__ver__/$QGIS_VERSION/g" construct.yaml
          sed -i '' "s/__shortver__/$QGIS_VERSION_SHORT/g" construct.yaml

      - name: 📦 Package
        shell: bash
        run: |
          source /Users/runner/.profile
          conda init bash
          conda activate constructor
          conda install conda-build
          conda build constructor
          conda install -c file://${CONDA_PREFIX}/conda-bld/ constructor
          constructor --platform=${{ matrix.platform }} .

      - uses: m-kuhn/action-tmate@patch-1
        if: always()

      - name: 📦 Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: '*.pkg'
